# Generated by Django 5.0.6 on 2024-05-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('mask', models.ImageField(blank=True, upload_to='masks/')),
                ('processed_image', models.ImageField(blank=True, upload_to='processed_images/')),
            ],
        ),
    ]
